Решил задачи 3
js-tasks-ru/jsbasic-20210906-2_catkitkat-ars pull request #3
Opened 2021-09-14 11:43 UTC by Catkitkatars

2021-09-14 11:43 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-14 19:46 UTC, SinimaWath requested changes

2021-09-14 19:46 UTC, SinimaWath commented on 2-module/1-task/index.js
> +      }
- if вложенный в if, зачастую излишне, давай сократим до одного if: `if (... && ....)`
- Если честно, в JS не принято использовать метки. И тут непонятно, зачем она нужна, даже если ее не будет, то циклы также будет выполняться итеративно

2021-09-15 05:20 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-15 05:21 UTC, Catkitkatars commented on 2-module/1-task/index.js
> +      }
Привет! Спасибо, исправил

2021-09-15 19:30 UTC, SinimaWath requested changes

2021-09-15 19:30 UTC, SinimaWath commented on 2-module/1-task/index.js
> +    }
Тут continue не нужен, будет также работать, цикл после первой итерации не заканчивается:
```
for (...) {
    if (typeof salaries[key] == 'number' && isFinite(salaries[key])) {
      sum += salaries[key];
    }
}
```

2021-09-16 07:15 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-16 20:08 UTC, SinimaWath approved these changes

2021-09-16 20:09 UTC, merged